version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - mart-network
    ports:
      - "3000:80"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - mart-network
    ports:
      - "5000:5000"

networks:
  mart-network:
    driver: bridge
